# Generated by Django 4.1.2 on 2022-10-19 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("POP", "Pop"),
                            ("RAP", "Rap"),
                            ("INSTRUMENTAL", "Instrumental"),
                            ("ROCK", "Rock"),
                            ("HIP_HOP", "Hip Hop"),
                            ("RNB", "R&B"),
                            ("JAZZ", "Jazz"),
                            ("CLASSICAL", "Classical"),
                            ("MULTI_GENRE", "Multi Genre"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Privacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")],
                        default="PUBLIC",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="song",
            name="genre",
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "playlist_cover",
                    models.ImageField(blank=True, upload_to="media/playlist_covers/"),
                ),
                (
                    "genre",
                    models.ManyToManyField(
                        related_name="playlists_genre", to="backend.genre"
                    ),
                ),
                (
                    "privacy",
                    models.ManyToManyField(
                        related_name="playlists_privacy", to="backend.privacy"
                    ),
                ),
                (
                    "song_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlists",
                        to="backend.song",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="song",
            name="privacy",
            field=models.ManyToManyField(
                related_name="songs_privacy", to="backend.privacy"
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="genre",
            field=models.ManyToManyField(
                related_name="songs_genre", to="backend.genre"
            ),
        ),
        migrations.AddConstraint(
            model_name="playlist",
            constraint=models.UniqueConstraint(
                fields=("id", "user_id"), name="playlist_keys"
            ),
        ),
    ]
