# Generated by Django 4.1.2 on 2022-10-19 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_alter_song_album_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlbumSong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="songgenre",
            name="song_genre_keys",
        ),
        migrations.RemoveField(
            model_name="song",
            name="album_id",
        ),
        migrations.AddConstraint(
            model_name="songgenre",
            constraint=models.UniqueConstraint(
                fields=("song_id", "genre_id"), name="song_genre_keys"
            ),
        ),
        migrations.AddField(
            model_name="albumsong",
            name="album_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="songs",
                to="backend.album",
            ),
        ),
        migrations.AddField(
            model_name="albumsong",
            name="song_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="albums",
                to="backend.song",
            ),
        ),
        migrations.AddConstraint(
            model_name="albumsong",
            constraint=models.UniqueConstraint(
                fields=("album_id", "song_id"), name="album_song_keys"
            ),
        ),
    ]
