# Generated by Django 4.1.2 on 2022-10-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_albumsong_remove_songgenre_song_genre_keys_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlist",
            name="song_id",
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("MAN", "Man"), ("WOMAN", "Woman"), ("OTHER", "Other")],
                default="OTHER",
                max_length=5,
            ),
        ),
    ]
