# Generated by Django 4.1.2 on 2022-10-19 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0007_remove_playlist_song_id_alter_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="song_id",
            field=models.ForeignKey(
                default=231,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="backend.song",
            ),
            preserve_default=False,
        ),
    ]
