# Generated by Django 4.1.2 on 2022-11-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0008_like_song_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="genres",
            field=models.ManyToManyField(
                related_name="playlists",
                through="backend.PlaylistGenre",
                to="backend.genre",
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="songs",
            field=models.ManyToManyField(
                related_name="playlists",
                through="backend.PlaylistSong",
                to="backend.song",
            ),
        ),
    ]
