# Generated by Django 4.1.4 on 2023-01-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0010_alter_user_gender_alter_user_is_artist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("MAN", "Man"), ("WOMAN", "Woman"), ("OTHER", "Other")],
                default="OTHER",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_artist",
            field=models.BooleanField(default=False),
        ),
    ]
