# Generated by Django 4.1.4 on 2023-01-18 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0012_alter_album_album_cover_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="like",
            name="like_keys",
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("id", "user_id")},
        ),
    ]
