# Generated by Django 4.1.4 on 2023-01-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0013_remove_like_like_keys_alter_like_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                fields=("id", "user_id"), name="like_keys"
            ),
        ),
    ]
