# Generated by Django 4.1.4 on 2023-01-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0014_alter_like_unique_together_like_like_keys"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="like",
            name="like_keys",
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("user_id", "song_id")},
        ),
    ]
