# Generated by Django 4.1.4 on 2023-01-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0015_remove_like_like_keys_alter_like_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="genre",
            field=models.ManyToManyField(related_name="songs", to="backend.genre"),
        ),
        migrations.AlterField(
            model_name="song",
            name="release_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
