# Generated by Django 4.1.4 on 2023-01-25 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0016_song_genre_alter_song_release_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SongGenre",
        ),
    ]
